### ISSUE TITLE
File/Image features

### ISSUE THREAD

**Issue by level09** [datazenit/sensei-grid#5]
This is a great project. was wondering if you thought about supporting other widgets such as files/images ?

**Comment by lauris** [comment]
Thanks for showing interest in Sensei Grid.  Yeah, I have definitely thought about supporting images/files, but I am not sure if that should be included in the main repo. In my opinion there is too much options on how to implement this (upload/preview) so I think that the best option is to leave this for the end developers to implement. Also I am thinking about moving all custom editors to separate repos and just leave the simple editor bundled with Sensei Grid.

**Comment by lauris** [comment]
I have added a setting to allow HTML in cells, this can be used to display an image in data grid. Please see #8 for related issue.
