### ISSUE TITLE
Is it possible to delete a row?

### ISSUE THREAD

**Issue by sstyle** [datazenit/sensei-grid#7]
Hi! Thanks for the great project. I can not find how to delete a row ( Can you help pls

**Comment by lauris** [comment]
Hi!

This functionality was added just recently, you can see it live here https://datazenit.com/static/sensei-grid/examples/

Use ``ctrl + backspace`` or ``⌘ + backspace`` to delete a row. You can also use ``ctrl + d`` or ``shift + d`` to duplicate a row.

**Comment by sstyle** [comment]
Thanks!
