### ISSUE TITLE
HTML code in cell

### ISSUE THREAD

**Issue by sstyle** [datazenit/sensei-grid#8]
Hi! I need to show HTML (link or <img>) instead a simple text. Is it possible?

**Comment by lauris** [comment]
Hi!

Currently all table contents gets escaped, but custom formatters could be developed to allow HTML nicely.

**Comment by sstyle** [comment]
Can you please give a more detail info how to do that?

**Comment by lauris** [comment]
I just added a setting to allow HTML in cells. For each column you want to allow HTML in, you must set ``allowHTML: true`` in column definition. 

Check full example under "HTML in Grid Demo" tab: https://datazenit.com/static/sensei-grid/examples/

**Comment by sstyle** [comment]
Thank you very much!

**Comment by sstyle** [comment]
Now it shows me a HTML code, but I can not click on link for ex.
